---
"%test":
  quarkus:
    hibernate-orm:
      log:
        sql: true

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
      sql-load-script: import-dev.sql

quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      max-size: 16
  flyway:
    migrate-at-start: true
  hibernate-orm:
    database:
      generation: none
    packages: de.renatius.poc.quarkus.library.entity
    sql-load-script: no-file
