---
version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: poc_quarkus
      POSTGRES_USER: poc_quarkus
      POSTGRES_DB: poc_quarkus
    ports:
      - "5432:5432"
