---
name: Analyze
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        language: ['java']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Environment for SuperLinter
        run: cat .github/super-linter.env >> "$GITHUB_ENV"
      - name: SuperLinter Scan
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: NOTICE
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.1.0
        with:
          args: --baseline,qodana.sarif.json
      - name: Upload Sarif file from Qodana
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
